### ISSUE TITLE
Interface needed for us to know if user accepted or not the Eula

### ISSUE THREAD

**Issue by RazorPT** [Carlosph/CookiesConsent#4]
Hi there this library is great but it would be really nice if library supported an simple interface to let us know if the user accepted or not the EULA. This is specially usefull for situations where we want to load ads or other stuff only if the user accepted the EULA.

P.S: About the mssage do you think that the message shown in the dialog is enough to be compliant? I ask this because the example on cookiechoices as a much bigger message with a lot more details.

**Comment by Carlosph** [comment]
Hi @RazorPT, thanks for the suggestion. You are right, in theory the code that uses the device identifier for ads, analytics and so on, shouldn't be run until the user closes the alert. I have added some code so you can implement that behavior if you want.

You can now set a listener to the `CookiesConsentOverlay` or `CookiesConsentDialog` implementing the interface `CookiesConsentListener` which has the method `onCookiesAllowed`. This method will be called when the cookies can be used, which is, when the user is not from EU or he has already being notified about the use of cookies.

You can also use the method `isConsentNeeded` on `CookiesConsentAlert` in case you need to know in your code if the user has yet to accept the policy.

Regarding the message, many websites are doing it this way. A short message linked to a privacy policy. I think that, if the privacy policy explains the use of the device identifiers and the third party services that are being used, there shouldn't be a problem with compliance. The second paragraph on the [compliance documentation of Cookie Consent by Silktide](https://silktide.com/tools/cookie-consent/docs/compliance/) express well how I see it.

Also, as a developer, If I have to show a message to the users I prefer it to be short and not scary, that's why I choose a text similar to the text used on many webpages.

I have created a PR so you can take a look at the new methods and make any suggestion if you will. In a few days I will merge it and publish the new version of the library.

Regards

**Comment by RazorPT** [comment]
Hi again thanks for adding the listener, i just review the code changes and it seems fine you can merge and publish a new version :).

I am just curious of something, since you are using the AlertDialog how you do prevent the window manager leak on screen rotate? Normally i had to convert all dialogs to DialogFragment to avoid this problem

**Comment by Carlosph** [comment]
I've already done the merging, updated the readme info accordingly, and pushed the new version to the Jcenter repository.

About the window manager leak you mention, I'm using the `AlertDialog` from the support library, which extends from `AppCompatDialog`. I haven't experienced any problem with screen rotation. Maybe the `AlertDialog` from the support library doesn't have that issue.

Thanks for the feedback, and your contribution.
